import { useState, type FormEvent } from 'react'
import { adminStoreApi } from '../api/storeApi'
import type { StoreDetail, StoreFormValues } from '../types/store'

const serviceOptions = [['IDENTITY_THEFT_REPORT', '명의도용 접수'], ['APPLE_AS', '애플 A/S'], ['FOREIGN_LANGUAGE_SUPPORT', '외국어 지원']] as const
const blankValues: StoreFormValues = { storeName: '', sido: '', sigungu: '', address: '', latitude: 37.5665, longitude: 126.978, phoneNumber: '', businessHours: '', serviceCodes: [] }
const valuesFrom = (store: StoreDetail): StoreFormValues => ({ storeName: store.storeName, sido: store.sido ?? '', sigungu: store.sigungu ?? '', address: store.address, latitude: store.latitude, longitude: store.longitude, phoneNumber: store.phoneNumber ?? '', businessHours: store.businessHours ?? '', serviceCodes: store.services.map((service) => service.code) })

export function StoreFormModal({ store, onClose, onSaved }: { store: StoreDetail | null; onClose: () => void; onSaved: () => void }) {
  const [values, setValues] = useState<StoreFormValues>(() => store ? valuesFrom(store) : blankValues)
  const [error, setError] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false)
  const set = <K extends keyof StoreFormValues>(key: K, value: StoreFormValues[K]) => setValues((current) => ({ ...current, [key]: value }))
  async function submit(event: FormEvent) { event.preventDefault(); setSubmitting(true); setError(null); try { if (store) await adminStoreApi.updateStore(store.storeId, values); else await adminStoreApi.createStore(values); onSaved(); onClose() } catch (caught) { setError(caught instanceof Error ? caught.message : '매장을 저장하지 못했습니다.') } finally { setSubmitting(false) } }
  return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><form className="faq-modal admin-store-form" onSubmit={submit}><h2>{store ? '매장 수정' : '매장 등록'}</h2><div className="admin-store-form__grid">
    <label>매장명<input maxLength={150} onChange={(event) => set('storeName', event.target.value)} required value={values.storeName} /></label><label>연락처<input maxLength={30} onChange={(event) => set('phoneNumber', event.target.value)} value={values.phoneNumber} /></label><label>시/도<input maxLength={50} onChange={(event) => set('sido', event.target.value)} value={values.sido} /></label><label>시/군/구<input maxLength={50} onChange={(event) => set('sigungu', event.target.value)} value={values.sigungu} /></label><label className="admin-store-form__full">주소<input maxLength={500} onChange={(event) => set('address', event.target.value)} required value={values.address} /></label><label>위도<input max="39" min="33" onChange={(event) => set('latitude', Number(event.target.value))} required step="0.0000001" type="number" value={values.latitude} /></label><label>경도<input max="132" min="124" onChange={(event) => set('longitude', Number(event.target.value))} required step="0.0000001" type="number" value={values.longitude} /></label><label className="admin-store-form__full">영업시간<input onChange={(event) => set('businessHours', event.target.value)} value={values.businessHours} /></label>
  </div><fieldset className="admin-store-services"><legend>제공 서비스</legend>{serviceOptions.map(([code, name]) => <label key={code}><input checked={values.serviceCodes.includes(code)} onChange={(event) => set('serviceCodes', event.target.checked ? [...values.serviceCodes, code] : values.serviceCodes.filter((value) => value !== code))} type="checkbox" />{name}</label>)}</fieldset>{error && <p className="login-error">{error}</p>}<div className="faq-modal__actions"><button className="secondary-button" disabled={submitting} onClick={onClose} type="button">취소</button><button className="primary-button" disabled={submitting} type="submit">{submitting ? '저장 중...' : '저장'}</button></div></form></div>
}
